### ISSUE TITLE
Update TrashCat repo with the latest version from Unity Asset Store

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/trashcat#4]
## Tasks
- [x] Download the latest version from https://assetstore.unity.com/packages/templates/tutorials/endless-runner-sample-game-87901 
- [x] In `PlayerData.cs` change `tutorialDone` to be `true` always in order to be able to generate builds for TrashCat without starting with the tutorial
- [x] Update the project with the downloaded version and changed script (see above) and push changes to `master` branch
- [x] Update the AltTester Unity SDK submodule 
- [x] Create `README.md` with relevant information for building manually
- [x] Update the repo for the latest changes in the `master` branch for building the app in pipeline for different platforms

**Comment by iulianatodoran** [comment]
@sandraaltom as agreed I will assign no release label, but I'll be working on the ticket ftm

**Comment by iulianatodoran** [comment]
I lnked a [newer PR](https://github.com/alttester/trashcat/pull/9) to avoid conflicts, as it already has the changes from the [older PR](https://github.com/alttester/trashcat/pull/5)

**Comment by SiminaRe** [comment]
WIP
✅ cloned the project, pulled the git submodule; together with Andrei, learned how to update the AltTester SDK submodule to the latest version; he also updated the README.md to include this extra step.
